// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPet struct {
	Name    string  `json:"name"`
	Type    *string `json:"type,omitempty"`
	OwnerID int32   `json:"ownerId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Pet struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	OwnerID   int32  `json:"ownerId"`
	OwnerName string `json:"ownerName"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
